name: Test APIs

on:
  push:
    paths:
      - "EC530/APIs/**"
  pull_request:
    paths:
      - "EC530/APIs/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: EC530/APIs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Adjust to your required version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install dependencies if you have a requirements file
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: python -m unittest discover -s . -p "test_*.py"
