name: Test Sockets (EC530) # Updated name slightly for clarity

on:
  push:
    branches: [ main ]
    paths:
      - 'EC530/Sockets/**'  # Only trigger on changes within this path
  pull_request:
    branches: [ main ]
    paths:
      - 'EC530/Sockets/**'  # Only trigger on changes within this path

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nest_asyncio
          # Consider adding a requirements.txt in EC530/Sockets/
          # and installing with: pip install -r EC530/Sockets/requirements.txt

      - name: Run Unit Tests
        # Updated working directory to match the path filter
        working-directory: EC530/Sockets
        run: python -m unittest discover -v
