name: Test Sockets

on:
  push:
    branches: [ main ]
    paths:
      - 'Sockets/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'Sockets/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nest_asyncio
          # Optional: if [ -f Sockets/requirements.txt ]; then pip install -r Sockets/requirements.txt; fi

      - name: Run Unit Tests
        # Run from the repo root ($GITHUB_WORKSPACE)
        # Use default discover: searches current dir and subdirs for test*.py
        run: python -m unittest discover -v
