name: Test Sockets Directory

on:
  push:
    branches: [ main ]
    paths:
      - 'Sockets/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'Sockets/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        # Checks out to $GITHUB_WORKSPACE (/home/runner/work/EC530/EC530)

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nest_asyncio
          # Optional: if [ -f Sockets/requirements.txt ]; then pip install -r Sockets/requirements.txt; fi

      - name: Run Unit Tests
        # REMOVE the working-directory directive, so it runs from the repo root ($GITHUB_WORKSPACE)
        # Python adds the current working directory to sys.path, so it can find the 'Sockets' dir
        # unittest discover will find tests in subdirectories by default
        # run: python -m unittest discover -v
        # Optional: If you ONLY want to run tests in Sockets, explicitly tell discover:
        run: python -m unittest discover -v -s Sockets -p 'test_*.py'
