# .github/workflows/test_final.yml

name: Test Client/Server Chat

# Controls when the workflow will run
on:
  push:
    branches: [ main ] # Or your primary branch name (e.g., master)
    paths:
      - 'Final_Project/**' # Trigger only if files in Final_Project/ change
  pull_request:
    branches: [ main ] # Or your primary branch name
    paths:
      - 'Final_Project/**' # Trigger only if PR affects Final_Project/

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Single job named 'test'
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Define strategy if you want to test on multiple Python versions
    strategy:
      matrix:
        python-version: ['3.10'] # Add other versions like '3.9', '3.11' if needed

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repository
      uses: actions/checkout@v4 # Use latest stable version

    # Sets up the specified Python version
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5 # Use latest stable version
      with:
        python-version: ${{ matrix.python-version }}

    # Installs dependencies - pytest and pytest-asyncio for async testing
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio
        # If you add external dependencies later, add them here or use requirements.txt:
        # pip install -r Final_Project/requirements.txt

    # Runs pytest, specifically targeting tests within the Final_Project directory
    - name: Run tests with pytest
      run: |
        touch Final_Project/__init__.py
        pytest
